### ISSUE TITLE
Filter by video length

### ISSUE THREAD

**Issue by cal2195** [whyboris/Video-Hub-App#11]
Just as you can filter videos by video resolution, it would be nice to be able to filter by video length as well.

Both an upper and lower bound would be good! 👍

**Comment by whyboris** [comment]
I'll work on getting this in 👍

**Comment by cal2195** [comment]
Have you started on this? 😄

If not - I wouldn't mind looking at this! 👍

**Comment by whyboris** [comment]
Haven't started yet -- feel free to give it a go.

I may be a bit finicky about the UI - how were you thinking of letting users choose the cutoffs?

ps - there seem to be two features, both we'd like to have eventually:
- filter by length using minimum and maximum time cutoffs
- _sort_ by length - ascending / descending (separate issue from this) 👍

**Comment by cal2195** [comment]
There's lots of sorting that would be nice! 👍 We should make the issues for them! (Maybe a parent issue, and one for each type)

And I was planning on copying the resolution filter, with 0->max_video_length, and some number of divisions in between... Haven't thought too much about it - have you any ideas? 💡

**Comment by whyboris** [comment]
We can easily detect the shortest and longest video within the hub - set those as cutoffs, and then have the two sliders as I have with the resolution filter.

What made me pause is that I custom coded the resolution filter sliders but not in a flexible-enough way that I could reuse the component. I've not looked into it in more than half a year -- perhaps it would be easy-enough to modify. Do take a look if it can be!

For the UI, I suspect a nice way to do it would be something like this:

```
above:          15min           45 min
bar:         ======0####0=============
below:     3min                                    1hr 24min
```

So that the min and max are always shown (below) and the cutoff is auto-updated as you slide the slider just above the div that you drag (minimum aligned left, maximum aligned right - so they never overlap even if close together)

Comments? 😃

**Comment by cal2195** [comment]
Added in #112!
