### ISSUE TITLE
Duration filter issues

### ISSUE THREAD

**Issue by cal2195** [whyboris/Video-Hub-App#132]
Some small issues with the current duration filter:

- [ ] It's possible to move less than min and greater than max!
- [ ] It's quite hard to accurately choose a time - maybe less divisions would be better?
- [ ] Consider using a logarithmic scale (do you really care about seconds above 30 minutes?)

**Comment by whyboris** [comment]
I love logarithms (math major here 😅 ) but I'm unsure how intuitive it would be to play with a slider that behaves that way. Also -- if it starts at 0, it would have a very fine resolution for short videos and a very coarse one for long ones. 

Since I don't quite know who this filter is meant for and how people will use it, it's hard to make good decisions 😓 

If it's easy to put in a log scale to play with it - to see how it behaves, it may be worth trying. Feel free to try fewer divisions too. 

Also please let me know if you prefer I take on this task 👍

**Comment by cal2195** [comment]
I see your point about the intuitive nature - just don't like the way it currently works! I'll play around with it a bit! 👍

**Comment by whyboris** [comment]
I tried a bit to make the displayed value to never go above the maximum possible, but it wasn't straight-forward so I decided to leave as is.

I've not been able to select a value that is less that minimum.

I'm not thrilled with the behavior I've implemented -- scrolling off the edge of the app drops focus on the button (this is intentional), but as a result it's a challenge to select the minimum value (unlike in other apps where you can just zip your mouse to the far left of the screen and it works. I'm unsure about how to solve that easily.

I'm willing to release version 2.0 with the behavior as is. I think this is a much-more-minor issue than most I need to finish before release 😓

**Comment by whyboris** [comment]
Needs CSS fixing -- when only 1 element is starred, the bar appears below.
Just needs a minor fix 👌

**Comment by whyboris** [comment]
#212 is a nice improvement / compromise:

The maximum is now `3rd quartile + 3 * IQR` (see PR for description) -- and advancing the slider to the right-most position shows "every".

The benefit is that if you have a 5hr movie (for whatever reason), but most of your movies are around 1.5hr mark, the slider might end up cutting off around 2.5 hours giving you a finer resolution with the slider in the range that matters ✅
