### ISSUE TITLE
Latest version of the app requires settings.json to be deleted before launch

### ISSUE THREAD

**Issue by cal2195** [whyboris/Video-Hub-App#158]
Due to some changes, the latest version of the app requires the `settings.json` file (in different locations depending on OS), to be removed!

We should detect this on launch and overwrite it accordingly! 😄

**Comment by whyboris** [comment]
I've come across that too 😞 but wasn't sure what the cause was. Thank you for creating the issue to keep track of it!

I was hoping that it was just weirdness since I made the _settings.json_ include image sizes for each view.

I was thinking that a good way forward would be to save the file as _settings2.json_ because the settings file is not backwards compatible with app version 1.x - and this filename change could save some headaches when users upgrade 👍 

Problem solved? :trollface:

**Comment by cal2195** [comment]
Sorry for the delayed response, this is a perfect solution! 👌
