### ISSUE TITLE
Better git flow

### ISSUE THREAD

**Issue by cal2195** [whyboris/Video-Hub-App#165]
I was thinking, maybe we should adopt a better git flow like [this](https://nvie.com/posts/a-successful-git-branching-model/)?

This would allow for a `develop` branch, so I could merge features in quicker with less merge conflicts, and keep master just for each stable release?

The link there has a nice explanation of an approach, and it would be quite nice to have release branches that we could cut off at certain points and just fix bugs before release!

Let me know what you think! 😄

**Comment by cal2195** [comment]
I also like the idea of not squashing or fast forwarding when merging, to make the git tree a lot easier to see what's been merged! 👍

**Comment by whyboris** [comment]
I'm not opposed to another git workflow; we could have a dedicated branch where new features are added before it is committed to _master_. Though, since we have releases very rarely, I don't mind pushing things to _master_ 👌 

Is one of the main benefits that we could merge less-complete features to a _develop_ branch (while we are reluctant to do that when merging to _master_)? And it would be most-beneficial close to the release of 2.0.0 because new features wouldn't get merged to _develop_ once it's "frozen" except for bug fixes, until it merges to _master_?

I know traditionally _master_ is reserved for solid code that has been thoroughly tested and released, but I've not followed that here with the project since no official release will happen until _master_ has been thoroughly debugged and tested and I'm ready for it 😅 

Sorry if I've misunderstood the benefits you see -- do let me know 👍 

Also, I'm ok with not squashing -- I thought it made the history a bit more readable, but I'm fine with it either way. I'm a little unsure where _fast forwarding_ occurs or how it differs from whatever other option there is. In other branches after _master_ is updated I just "git checkout master; git fetch; git pull origin master; git checkout other-branch; git merge master" 🤔

**Comment by whyboris** [comment]
Happy to discuss further, closing as part of _Issues_ cleanup before version 2 release (around 2 weeks from now 🎉 ). 

I think I've not changed my mind since my above comment (@cal2195 please feel free to comment or comment-and-reopen the issue) 👌 

ps - Cal, I believe you have enough permissions on this repository to push branches to it -- so if you prefer to have them here, rather than on your _fork_, please feel free 👍 

I have no problem with unmerged feature branches hanging around. Feels like a branch-per-feature is easy enough, rather than having a `develop` branch which gets all features merged in (though perhaps I've misunderstood your comment). Cheers 😄
