### ISSUE TITLE
Clip fixes

### ISSUE THREAD

**Issue by whyboris** [whyboris/Video-Hub-App#185]
I'd like to have an option to disable sound on the _clip_ view
Also have a short random timeout before a clip starts playing (when all clips are playing) so that the app doesn't try to access 20 files all at the same time 😅

**Comment by cal2195** [comment]
+1 for the sound option! 👍 

Timeout sounds interesting - I wonder if it would have much of an effect since you'll need to read them all anyway, but it could be a good idea! 👍  What range of values were you thinking? Wouldn't want to make it too jarring either - I wonder what random vs sequential would look like? 😄

**Comment by whyboris** [comment]
I'll play around with values to see what feels good, but probably sub-500ms (maybe 350 even).

Another part of the reason is that if all videos start at the same time, they all switch between the extracted sub-sections at the same time, it's a bit jarring -- too coordinated.

**Comment by whyboris** [comment]
#189 will 
- add a random delay for video start
- add settings button to disable sound when hovering on a clip

I decided not to mess with delaying loading of all the videos in view -- I hope each OS will handle it gracefully 😅
