### ISSUE TITLE
Background Initial File Scan and Metadata Import

### ISSUE THREAD

**Issue by cal2195** [whyboris/Video-Hub-App#23]
To be truly fluid, the app should scan for files and import them fully in the background, updating the UI as files are imported, just like the thumbnail extraction! This would also allow you to resume importing files if you close the app and reopen it.

This would be a lovely feature, but would probably need significant changes, particularly around updating the file list to display, tags, and metadata displayed by each item.

@whyboris Do you have any thoughts on this?

**Comment by whyboris** [comment]
I see the benefit of having the gallery populate one file at a time - as the screenshots become available, but I still think the current setup is better.

Because importing screenshots takes a while, the app will be virtually non-operational (with respect to exhaustive search) if we don't show the files in the app until they are scanned. For example, you have hundreds of cat videos, you start the scan, and then decide to search for a video with the word "cat" in its title. Virtually nothing will show up in the system you describe; currently -- all the videos will show up, but the previews would be missing.

The resuming of importing files seems to be a feature we can implement without having files added to the gallery only when their screenshots become available. 

Though I feel like I may have misunderstood what you meant 😓

**Comment by cal2195** [comment]
For now, it's not too big a deal! Might be nice in the future, although I think we'd have to work around the gallery flicker issue - not much use if you still have to wait for the entire thing to happen anyway! 👍 

Maybe there could be an update item method to just add the new metadata? Low priority for now anyway! 😄

**Comment by whyboris** [comment]
Another reason I may have explicitly locked the screen is the fear that users will get into a weird state if they have access to the _settings_ menu -- they could try to open the _wizard_ again.

Partially it was to make my life easier -- no need to think through the multitude of edge-cases (are all time and sizes 0? no problem, but we'll need the display pipes to handle these values differently perhaps?)

It's hard for me to get excited about this feature while we have so many juicy ones in the pipeline 🙌

**Comment by whyboris** [comment]
@cal2195 -- please feel free to re-open the issue if you'd like - just add a comment.

I'm thinking we'll keep the app behavior as is now with no changes for the long foreseeable future.
