### ISSUE TITLE
Thumbnails broken with clips view and no autoplay

### ISSUE THREAD

**Issue by cal2195** [whyboris/Video-Hub-App#273]
Haven't looked into this deeply yet, but just wanted to report it to make sure it wasn't just me.

With the latest master, if you go to the clips view without autoplay videos enabled, the thumbnails don't appear until you hover over each clip?

Maybe I've done something silly! 😅

**Comment by whyboris** [comment]
I wonder if it's because you're opening an old `vha2` file 😅 
In the last few months, at some point, I made it so that the first thumbnail for each clip resides in the `/clips/` folder. Please let me know if you have something different 🙆‍♂

**Comment by cal2195** [comment]
This appears to be the case! 👍 Is this for performance?

**Comment by whyboris** [comment]
I remember you recommended that the first screenshot to be shown for the video would be the same as the first frame of the video -- so I decided to have the regular thumbnail different from the video thumbnail. 

The process currently extracts the first screenshot of the video, then the filmstrip, then the clip, and finally the video thumbnail.

The biggest downside is that the clip thumbnails are different from the regular main thumbnail. But because people extract clips and screenshots at different resolutions, it's likely that the video resolution will be much lower (and less pretty).

Feel free to comment and/or close the issue 🙇

**Comment by cal2195** [comment]
Sounds good to me! 😄
