### ISSUE TITLE
Display word cloud in the Mac Touchbar

### ISSUE THREAD

**Issue by cal2195** [whyboris/Video-Hub-App#306]
It would be really cool to display the word cloud in the touch bar, next to the currently implemented buttons! 💡 

Main features include:
- Number of tags - Not sure how many the touch bar can have, so maybe implementing the extended word cloud is unfeasible... 🤔 
- Updating as you search/tag - This is important, it needs to update the list, just like the word cloud as you search and filter! 👍 
- Random tags - it would be a cool addition to have the option display a random selection of tags from the currently visible videos! ⭐️ 
- Number of videos matching the tags - Maybe have the number of videos that would be left, if you selected a tag, beside it, like `Movie (2048)` 😄 

Any and all comments and suggestions appreciated! 💯 

I'm also open to anyone looking into this, if they feel inspired! 😃

**Comment by whyboris** [comment]
🤔 there hasn't been any comments on this in over a year -- seems like not a very in-demand feature 😅 

I have added a `Word cloud` tray on the bottom of the app - which lets you see ~100 tags. 

Since the mac touch bar would only have room for ~10 tags, seems like not a very useful feature 🤷 

I'm closing the issue. Please feel free to comment if you think I should reopen 🤝
