### ISSUE TITLE
Filter: Display resolution more accurately

### ISSUE THREAD

**Issue by Aer20** [whyboris/Video-Hub-App#395]
The current scale is too coarse and therefore not helpful enough.

My feature request is to change the resolutions in the slider for filtering:

Name in Slider: Range of video height
120p: 0-199
240p: 200-319
360p: 320 - 439
480p: 440 - 535
576p: 536 - 679
720p: 680 - 1039
1080p: 1040 - 1399
1440p: 1400 - 2119
2160p: 2119 - 2839
2880p: 2840 - 4279
4320p: 4280 - 10000

This would be very helpful for the usage of the program.

**Comment by whyboris** [comment]
I agree that the resolution filter is rather coarse. 
Visually it would be a bit tricky to implement a more-fine-grained selector.

I guess the resolution filter could be changed to behave more like the _duration filter_ but then it would lose the histogram (which I hope is useful to at least some users).

As in my other comments to the issues you posted I'm happy to show you which code to edit to get a custom version of this to work on your end. A big challenge in getting a feature like this into the app is the work required to make it bug-free and pretty and intuitive to use; getting it to work for a private copy is easier because you can shrug off the bugs and the lack of polish 🤷

**Comment by whyboris** [comment]
I'm closing this issue as there doesn't seem to be more interest in it.

Please feel free to comment / reopen / open a new issue if you'd like 👌
