### ISSUE TITLE
Delete does not work over network drives

### ISSUE THREAD

**Issue by Aer20** [whyboris/Video-Hub-App#397]
When i open a Hub from a network drive, e.g. from drive "z:" which lays on "\\nas\share" and i try to delete a video, nothing happens. 
I have full rights on the drive, on the command line or the windows explorer i can delete the videos.

**Comment by whyboris** [comment]
Thank you ... I believe this may be because the app tries to move the file to the recycling bin.

In order for this to work, you may have to enable this in the OS:
https://www.remosoftware.com/info/enable-recycle-bin-mapped-network-drives

I've not tested things yet. At the moment I'm very uneasy about deleting the file without it going to the recycling bin (I want users to be able to undo a delete). So the above may be the only solution (and if it works I should add it to the FAQ).

**Comment by Aer20** [comment]
I did it according to the instructions. 
I can also see the network drive in the trash, so the instructions worked formally.
However, I cannot delete any files in the Explorer afterwards. Maybe it's because I'm using a notebook or it doesn't work with the latest cumulative update of Windows 10 or maybe because the notebook is in the corporate domain and the host PC is in a workgroup.
If I change in the local Recycle Bin settings that files on the letter should be deleted immediately, I can delete files in the Explorer again.

But in no setting i can delete a video in Video Hub App.

Regardless of this, it is difficult in (slow) WLAN when large files are transferred to the local recycle bin via WLAN.
I would make it possible to delete files without the Recycle Bin as an option with the warning "at your own risk".

**Comment by whyboris** [comment]
I'll test out my network drive and trash sometime this week 🤞 and report back with what I find.

I don't imagine that deleting something on the network drive should transfer it to your local recycling bin -- it should delete the file to the recycling bin of the remote OS you're connecting to 🤔 

If I can't make it work, maybe I'll add a "super-dangerously-delete" option 😅

**Comment by nickrowland** [comment]
> 
> 
> Thank you ... I believe this may be because the app tries to move the file to the recycling bin.
> 
> In order for this to work, you may have to enable this in the OS:
> https://www.remosoftware.com/info/enable-recycle-bin-mapped-network-drives
> 
> I've not tested things yet. At the moment I'm very uneasy about deleting the file without it going to the recycling bin (I want users to be able to undo a delete). So the above may be the only solution (and if it works I should add it to the FAQ).

FYI this worked for me. I did map to a new network drive to follow the instructions and had to update the inputDir in the vha2 file to point to the new mapped location (replace all, old location to new). I can now delete!

Thanks!

**Comment by atyourservicesire** [comment]
> 
> 
> I'll test out my network drive and trash sometime this week 🤞 and report back with what I find.
> 
> I don't imagine that deleting something on the network drive should transfer it to your local recycling bin -- it should delete the file to the recycling bin of the remote OS you're connecting to 🤔
> 
> If I can't make it work, maybe I'll add a "super-dangerously-delete" option 😅

Hi Boris. I would really like to see that "super-dangerously-delete" option added 👍 

As of right now, it's kind of difficult to manage your video library if you have it stored on your NAS, since you have to first locate the files in your directory, delete them, and then rescan your library.

I appreciate the guide but I did not manage to get it to work, and I don't really wish to map the drive and/or link the user profile folders to the share.

Hope you will consider adding the option some time in the future.

Cheers.

**Comment by whyboris** [comment]
Great idea @atyourservicesire 🤝 

I'll add the "super-dangerously-delete" option in the future #438 (or as soon as someone creates a PR for it 👍 )

**Comment by whyboris** [comment]
@jamesd35 added the "super dangerously delete" option 🎖️ ! It will be released in the v3.0.0 (the next) release 🎉

**Comment by whyboris** [comment]
Closing this issue as I think we have a working solution ✅ 

Please feel free to comment if you'd like 👍
