### ISSUE TITLE
Clicking on any word(s) in auto-generated tags finds nothing

### ISSUE THREAD

**Issue by whyboris** [whyboris/Video-Hub-App#403]
Turns out at some point the app started using the "tags include" filter rather than "video name has" search filter when clicking on a tag inside the _Auto generated tags_. The result is _no_ videos found 😢 

Fixing ASAP -- though anyone is welcome to open a PR if you get there before me 😉 

_edit:_ I think this only happens when you disable the manual tags in the settings

**Comment by LordJon** [comment]
Sorry if this isn't related but I've noticed that if I remove auto generated tags (because they made no sense for a human) and I close the application in the way that does save settings (I'm aware of that bug haha) after a while I notice the tags to be back.

**Comment by whyboris** [comment]
Thanks LordJon -- I'll take a look. I rarely use the _auto tags_ and haven't removed anything since I  was testing the feature as I built it.

The way the removal of auto-generated tags works is that it adds the word / words to a `remove` list inside the `.vha2` file. And the auto-tags are always auto-generated (never stored); once they are generated, any that match those on the `remove` list are removed from view 😅 

I'll see if I can replicate the bug.

**Comment by martincaron** [comment]
Took a look at the initial issue with a wider lens today. I've occasionally been getting `0 videos found` in situations when I was expecting a different behavior based on my library. Use Cases : 

**The Word Cloud uses the** :
-	A) `VideoName` filter on a `folder-tag` with manualTags=`false`
-	B) `VideoName` filter on a `file-tag` with manualTags=`false`
-	C) `VideoName` filter on a `folder-tag` with manualTags=`true`
-	D) `VideoName` filter on a `file-tag` with manualTags=`true`
-	E) `VideoName` filter on a `manual-tag` with manualTags=`true`
-	`manual` tags are not rendered when manualTags=`false`

**The Details views uses the** : 
-	F) `Tags` filter on a `folder-tag` with manualTags=`false`
-	G) `Tags` filter on a `file-tag` with manualTags=`false`
-	H) `Tags` filter on a `folder-tag` with manualTags=`true`
-	I) `Tags` filter on a `file-tag` with manualTags=`true`
-	J) `Tags` filter on a `manual-tag` with manualTags=`true`
-	`manual` tags are not rendered when manualTags=`false`

**The Meta Bar in the Sheet view uses the** : 
-	K) `Tags` filter on a `folder-tag` with manualTags=`false`
-	L) `Tags` filter on a `file-tag` with manualTags=`false`
-	M) `Tags` filter on a `folder-tag` with manualTags=`true`
-	N) `Tags` filter on a `file-tag` with manualTags=`true`
-	O) `Tags` filter on a `manual-tag` with manualTags=`true`
-	`manual` tags are not rendered when manualTags=`false`

**The Auto-Generated dialog uses the** : 
-	P) `Tags` filter on a `file-tag` with manualTags=`false`
-	Q) `Tags` filter on a `file-tag` with manualTags=`true`
- 	`folder-tags` are not rendered here
-	`manual` tags are not rendered here

**The Manual tag tray uses the** : 
-	R) `Tags` filter on a `manual-tag` with manualTags=`false`
-	S) `Tags` filter on a `manual-tag` with manualTags=`true`
-	`auto-tags` are not rendered here


**The following uses cases caught my attention** : 
- `A` & `C` are an issue if the folder-tag does not also repeat itself in the filename. For example, I have hundreds of videos under folder `Movies` but never repeat the word `Movies` in the filenames, therefore 0 results. Use cases `F` and `K` solve this by using the `Tags` filter instead.

- `E` is an issue if you don't have the manual tags serialized in the filename. Use cases `J`, `O` & `S` solve this by using the `Tags` filter instead.

- Use case `R` returns 0 results 100% of the time because the `Tags` filter is affected by manualTags=false


@whyboris , your initial comment leads to believe there is a good reason for using `VideoName` filter in both the Word Cloud and the Auto-Generated dialog (although it now uses the `Tags` filter). I can't figure out why we wouldn't stay consistent accross the board and use the `Tags` filter. So wanted to open the discussion before attempting any work.


**My proposition would be to** :
- Use the `Tags` filter accross the board for consistency. Therefore change the World Cloud to use the `Tags` filter instead. This would solve `A`, `C`, & `E`.
- As for `R`, maybe the issue is that we are showing manual tags in the tray despite the option being turned off, but I have a hunch that the `show-manual-tags` option was not intended to affect the tag tray. Maybe we should allow the `Tag` filter to return videos containing manual tags despite the option being turned off and keep the tag tray as-is.

Cheers!

**Comment by whyboris** [comment]
I'll answer more-fully shortly, but the short back story is that in version 1.0.0 I didn't have tags, and then sometime in version 2.0.0 there were tags. I still haven't used the feature personally, but enough people have asked for it so it's now there.

Basically, I hadn't spent enough TLC (tender, loving care) on the feature to address whatever issues crept up while adding the feature 😅 

I'll post a more-thoughtful response within the hour 🤝

**Comment by martincaron** [comment]
ah! That makes a lot of sense!
No rush at all, I've been enjoying working this app. 🤝

**Comment by whyboris** [comment]
Great to hear! 
Check out the `RegEx` PR I just merged 😉 #427 😎

**Comment by whyboris** [comment]
Thank you @martincaron for the ideas here: https://github.com/whyboris/Video-Hub-App/pull/437#issuecomment-633732164

I'm open to suggestions and a deeper redesign 👍

**Comment by whyboris** [comment]
I'm fixing the initial issue with #568 -- by enabling the `autoFileTags` if it's disabled 😓 

I'll see if any other ideas / proposals raised in this thread are important to fix before releasing `3.0.0` 😅 🤝 🙇

**Comment by whyboris** [comment]
Closed with #568 😅 the PR does not address every concern raised in this _Issue_. Please feel free to comment, reopen, or create a new issue 🤝
