### ISSUE TITLE
Batch adding of tags

### ISSUE THREAD

**Issue by whyboris** [whyboris/Video-Hub-App#404]
I thought about it, should be simple.

- batch editing mode toggled with a button
    - => opens thumbnails view
    - => opens the manual tag tray
    - => tray shows message "select as many videos as you'd like and click on a tag to add the tag to all of them"
- clicking on any video adds a large checkmark ✅ to indicate "selected" 
    - => adds `selected: true` to _ImageElement_
- clicking on any tag in the video tray adds the tag to all those videos

🤷 some users have been insisting that batch adding of tags is important to them. Seems like an easy-enough implementation as described above 🤞 

I'll implement it unless someone wants dibs 🤝

**Comment by LordJon** [comment]
Oh that would actually be very helpful. I'm going to use VHA for organising films for a film festival. Making it possible to quickly tag multiple video's this way would make tags a lot more useful!

**Comment by whyboris** [comment]
I'll try to finish the feature today -- it's functionally 90% there, just need to make the UI (user interface) intuitive / self-explanatory 😊 

Thank you for words of encouragement (knowing a feature is useful to others is motivating) 🤝

**Comment by LordJon** [comment]
You're welcome Whyboris. The whole app makes life a lot more easy for film festivals, especially during selection with this tagging functionality.

I'm a bit of a lurker around here but if you like it I'll make a new feature request here instead of adding it to other posts haha. At least if that's something useful for the development.
