### ISSUE TITLE
[shortcuts] Toggling Minimal/Kiosk mode does not hide Tag Tray

### ISSUE THREAD

**Issue by martincaron** [whyboris/Video-Hub-App#441]
Pretty simple one : 
- If Tag Tray is already open and then Minimal/Kiosk mode is activated 
- Then the Tag Tray remains open/visible.

My expectation would be for the Tag Tray to follow suit, and hide itself like the rest of the surrounding containers. 

It could always be retoggled afterwards with the soon-to-be Issue #435

**Comment by whyboris** [comment]
Great catch! I've not used the shortcut since I added it to the app, and the _tag tray_ was added only recently 😅 

PR welcome for _also_ minimizing the _tag tray_ (also please glance if the "similar videos tray" also minimizes if it's open). 🙇 

This is likely a few lines of code only; I think it's good to leave it for `good first issue` for anyone who is just starting out with coding or with GitHub and wants some light practice 👍 

If the task isn't done before next version release (at least a month or two away), I'll fix it before the release 👌

**Comment by whyboris** [comment]
ps -- this is better to fix after #443 merges -- since the PR touches a lot of the shortcut code 👍

**Comment by whyboris** [comment]
@martincaron -- I finally merged #443 😅 -- would you like to add this code yourself?

Cheers 👋

**Comment by whyboris** [comment]
Thank you @orkomlosh for the fix #494 🎉
