### ISSUE TITLE
Add recently opened items to taskbar / dock

### ISSUE THREAD

**Issue by whyboris** [whyboris/Video-Hub-App#459]
Should be relatively easy 🤔 

https://www.electronjs.org/docs/tutorial/recent-documents

1) After app starts send over the list of 'recently opened', and in `main.ts` just:
```
app.addRecentDocument('/path/to/recently/opened/file.vha2');
```

2) When user clears recently-shown in the app, send over to `main.ts` a message and:
```
app.clearRecentDocuments();
```

👍

**Comment by hrhan** [comment]
Hi @whyboris can I take this one if it's still available? :)

**Comment by whyboris** [comment]
Hey @hrhan -- awesome that you're interested in implementing this 🎉

Please feel free to reach out with questions or if you have any trouble with the code 👍

If you have no strong preference, please consider basing your PR off the `video-hub-app-3` - though it's fine if you work off `master` too 🤝 

Cheers 😊

**Comment by hrhan** [comment]
Great, thank you! I'll go ahead with the `video-hub-app-3` branch as the base then.

**Comment by hrhan** [comment]
Hi, here's what I have so far:
- added the call to `app.addRecentDocument() ` inside `openThisDamnFile()`
- modified `clearRecentlyViewedHistory()` to send a message to ipcMain which will then call `app.clearRecentDocuments()`

I think recent documents list should work in mac now. (but I don't have a mac to test with 😅) 
It turns out windows 10 is not suitable for testing this feature as it seems to enable recent documents list when the app is set as the default file handler for vha2 files even without the call to `app.addRecentDocument()`. One option I can try is `app.setJumpList()` and see if that lets me control the recent documents list..

**Comment by hrhan** [comment]
I found a bug on windows that if you try to open a vha2 file while the app is already running, it throws an error saying "File not found: --allow-file-access-from-files". This seems to happen because when `second-instance` fires, `argv` actually contains the file path as the last item and the option `--allow-file-access-from-files` as the second item. I'm using Windows 10 and not sure if this is the case for other os's. I can try fixing it this way:
`if (argv.length > 1) {
    openThisDamnFile(argv[-1]);
}`

**Comment by whyboris** [comment]
Thank you @hrhan 🎉 

Could you submit a pull request with your changes? I have both Windows 10 and Mac so I could test and see how it works.

Great catch on the Mac bug! The "openThisDamnFile" function has been around since version 1 of the app - named so because of the frustration I had getting VHA to run as a single instance _and_ open the files users would click 😅 

I've not revisited that functionality much since it worked well-enough - but I'd rather not have any "File not found" errors pop up during regular use. If you see that your change fixes the problem and doesn't seem to cause other problems, please open a separate pull request (or include it as part of your "recent items" change 🤝 🙇 

Cheers!

**Comment by hrhan** [comment]
Oh awesome! It would be great if you could tell me if the new feature works in mac :)

And yeah, I totally understand your frustration when it comes to file I/O's. I was surprised to see this "file not found" error, but at least it's fixed on my end. Hopefully it doesn't happen for other people as well.

It seems like I can't submit a pull request for each commit after I pushed them 🤦. 
I hope it's ok to include them in one pull request..
Anyways, I've made the pull request here: #485 
Please let me know if there's anything breaking because of my changes!

**Comment by whyboris** [comment]
Thank you @hrhan for the feature addition 🙇 #485
