### ISSUE TITLE
Sort files with numbers in increasing order, not lexicographically

### ISSUE THREAD

**Issue by whyboris** [whyboris/Video-Hub-App#463]
Currently files are sorted:
```
1, 10, 11, 12 ... 2, 20, 21, 22 ... 3, 30, 31 ...
```
rather than 
```
1, 2, 3 ... 10, 11, 12 ... 20, 21, 22 ...
```

Might not be annoying to fix, but leaving the issue open in case someone wants a challenge 🤷

**Comment by cal2195** [comment]
Got you sorted: https://www.npmjs.com/package/natural-orderby

Geddit? 😅  

```
paths = ['01 first', '10 fourth', '1 second', '2 third']
console.log('before: ' + paths)
console.log('after:  ' + window.naturalOrderBy.orderBy(paths))
```

```
"before: 01 first,10 fourth,1 second,2 third"
"after:  01 first,1 second,2 third,10 fourth"
```
https://jsfiddle.net/8xgtwL05/

**Comment by whyboris** [comment]
I love it!

ps - what's "Geddit"?  😅

**Comment by HerrRobo** [comment]
Hello, is this issue still open? 
If so, I'd like to help out - first timer here!

**Comment by whyboris** [comment]
Hello @HerrRobo -- thank you for your interest 😁

Please feel free to give this a try and reach out if you ever have trouble or questions.

Are you also thinking of using the `natural-orderby` package to simplify the task?

Cheers 🤝

**Comment by HerrRobo** [comment]
Sounds great, thanks!
Yep, my current approach is to look at natural-orderby that cal2195 suggested, which I believe would be used primarily in the sorting pipe class.

If this ends up being the approach accepted, the natural-orderby package would be a new dependency added to the project as well - obvious, but just a heads up anyway 😁

**Comment by Tundeh** [comment]
is this issue still open? If yes, i would like to take it.

**Comment by orkomlosh** [comment]
hey, let me know if you need help here, I can try and take it

**Comment by whyboris** [comment]
@HerrRobo -- would you prefer to keep working on it or are you OK with @orkomlosh taking it? I glanced at your fork of VHA and don't yet see a branch for this issue 🤔 please let us know 👍

**Comment by HerrRobo** [comment]
@whyboris Hello, sorry for the delay here. My fork has been updated and now contains a new branch which includes the natural-orderBy dependency. The results from sorting numbers naturally Alphabetically ascending/descending appears to work as intended, but I am unsure if the rest of my sorted test files are being sorted correctly from this approach. I need a deeper understanding into natural ordering, so I won't be making a PR from this if it happens to not be enough. 

Unfortunately I am unable to investigate much further because of personal time constraints, so feel free to take over @orkomlosh ! By all means, use the contents of my branch if it helps with a working solution! Best of luck!

**Comment by orkomlosh** [comment]
@HerrRobo thanks! i'll try to see if i can get to it also.
I went through your branch, it seems ok,
you just meant that you want to test it with more test files and naming? to see if it really fixed it?

**Comment by whyboris** [comment]
Thanks @HerrRobo for the update and your work 🙇 
Looking at it: https://github.com/whyboris/Video-Hub-App/compare/main...HerrRobo:sort-files-with-numbers 
It seems like all that would be needed 🤔

**Comment by whyboris** [comment]
Thank you @HerrRobo for the work -- I suspect we're 99% of the way there with your code, so I created a PR with it -- I hope you do not mind 🙇 #540
