### ISSUE TITLE
Update file metadata after video file is edited

### ISSUE THREAD

**Issue by litelime** [whyboris/Video-Hub-App#469]
**Issue 1**: Video metadata (size,duration) in app is incorrect after editing a video. 
**Issue 2**: If using the option of "Open video at time of clicked screenshot" the edited video will fail to open, I assume this is due to those times not existing in the new edited video.
Potential Solution: The ability to re-scan/update this video metadata
Details: Sometimes I have added a video to the app, but will end up editing that video to make it shorter, or merge two videos into one. 
As long as the file name is the same the app still recognizes it as the same video which is good, but the video size and duration will be off. 
One workaround would be to just change the name of the new edited file so it is detected as a new video in the app, but I don't want to lose custom tags or star ratings associated with the video

**Comment by whyboris** [comment]
Hello @litelime -- I'm sorry I completely missed this issue! 😱 

Thank you for describing what you're doing to cause _Issue 1_: you have a file "video.mp4" which you re-render with a video editor, so the "video.mp4" is now a different video than the original, but the app can't tell.

I think re-scanning makes sense, though I'm unsure how common this problem is. As far as I can think (at the moment), a re-scan would literally need to re-check every single video in your hub. Perhaps it's not a big issue with a hub composed of < 100 files; otherwise it will take a long time for almost no benefit (updating 1 video).

_as you note:_ One simple option is to simply rename the video file through your OS - and then re-scanning will automatically notice the new file and import it. Version `3.0.0` will have a better ability to do this -- automatically deleting from the hub the old video file.

Also, VHA `3.0.0` will have a "watch folder" feature, so it would perform the update as soon as you rename the file. There's even a chance (I've not tried) that if you're "watch[ing] folder" it will automatically detect when the video is re-rendered 🤞 

But any kind of re-scan (the one I describe above or otherwise) will lose the custom tags you have -- because it will recognize the video as a new file. Sorry 😔 

_Issue 2_ - have any videos ever opened at the time of clicked screenshot? Is it that you couldn't get the feature to work with your video player, or that it doesn't work for _some_ videos?

**Comment by whyboris** [comment]
@litelime -- please feel free to comment below or open a new issue 👍 

I'm closing it as I think my response has addressed it and I'm trying to clean up the _Issues_ board before releasing `3.0.0` 🚀
