### ISSUE TITLE
VHA 3 breaks relative folder paths feature

### ISSUE THREAD

**Issue by cal2195** [whyboris/Video-Hub-App#525]
Just trying out the new VHA 3! 🎉 

Relative paths don't seem to work anymore from VHA2 #8 - `inputDirs[0]` gets set to an empty string, causing GUI issues, along with "Folder not connected"!

Not sure if this was already on your radar! 😄

**Comment by whyboris** [comment]
I never put the vha file next to my videos -- and haven't tested this feature since implementing 3.0.0 changes 😓 

Thanks for putting it on the radar 🙇

**Comment by whyboris** [comment]
@cal2195 -- I believe this issue has been fixed at some point somehow 😅 
I tested recently and it seems to be working: 
  - during the wizard you can select an input folder
  - do not change the output folder (so the vha file and its associated folder is in the same spot as the videos)
  - extract -- and it seems to work 😅 

I'm closing as I suspect it works -- but please, if you have a moment, could you check on your end with the settings that caused the error before and let me know if it breaks 🙇 (no rush, and no worries if you don't get to it) 👌

**Comment by sense47** [comment]
Sorry to comment on a closed issue, but I just updated from VHA2 and I am noticing this issue. I have content on an external drive, with the vha2 file on the drive, sort of like an index. 

When I move the drive from computer to computer, if the drive letter changes, for example, all links to the videos in the hub are broken. In VHA2, the videos worked fine. 

I may be an edge case, I can manually change the drive letter to restore the links, but it's a bit of a pain. Just wanted to bring it up. Thank you so much!!

**Comment by whyboris** [comment]
No need to apologize -- thank you for the comment @sense47 😁 

I have stripped out the relative path because it was adding complexity with (to me) seemingly little benefit to the user.

But thanks to your example I see the point of having a relative path. I'll take a look to see if it's easy-enough to add back in relative paths without introducing bugs or too much complexity (which can result in bugs).

As for a **solution** for you, there is no need to manually change the drive letter. The easiest approach is to go to *Settings* (gear on top right), click on *Current hub* (4th tab) and click on the `not connected` (it's a button even though it look like just text) - and then with the "open folder" dialog that pops up, just point the app at the folder where your videos are.

Please let me know if the solution doesn't work for you.

Cheers!

**Comment by sense47** [comment]
WOW! That solved the problem! Thanks so much for the tip!
