### ISSUE TITLE
Video Hub App 3: Duplicate entries in VHA

### ISSUE THREAD

**Issue by CrendKing** [whyboris/Video-Hub-App#552]
I have "watch folder" enabled. Sometimes when it found a new video, it creates multiple duplicate entries in the VHA. These entries have exactly same properties, including hash. The only way I find to eliminate them is manually edit the file, which is painful.

I wonder is the hash unique enough to be trusted a key to each entry, so that instead of having the `images` as an array, make it an object, with hash as the key, so that it is more robust and never duplicates? Otherwise, we might need a "cleanup" or "dedup" button, because according to [Murphy's law](https://en.wikipedia.org/wiki/Murphy%27s_law), nothing prevents the app from creating duplicate entries.

**Comment by whyboris** [comment]
I've not tested the "watch folder" feature still (other than once to see that it detects changes) 😓 

I'm unsure at the moment whether it's because the `chokidar` library I'm using emits more than once when it finds changes or for some other reason.

I have implemented an `alreadyInAngular` variable to keep track of what has been added (see `main-extract-async.ts` file). Perhaps it's a matter of updating it during "watch folder" 🤞 

The hash is unique and that is how I find duplicates (for times when the file exists twice in a hub) 👍 But given that the entire architecture of the app revolves around the images _array_ I don't think I'd want to represent the data in any other way.

The app _should_ be able to create duplicate entries - unless the file name and file path are identical (that is the individual file is about to appear twice -- as in the bug you're describing).

This is why I'm sure it will take me at least a month, and perhaps 2 months, to get the version 3.0.0 out -- there's still so much cleanup to do around edge cases 😓

**Comment by whyboris** [comment]
Related: #557

**Comment by whyboris** [comment]
I found a related bug. Turns out `chokidar` disregards `persistent` flag when `fsevents` is not enabled. This means `chokidar` continues to _watch_ a folder.

To replicate:
1) open a hub
2) rename a file using the OS
3) notice the new file is added to the gallery

I'm going to fix this misbehavior with the next commit on #573 😎

**Comment by whyboris** [comment]
I was able to replicate the problem. Since `chokidar` was in persistent watching state, it would detect a new file was found and would add it (even though we renamed the file through the app).

I have an idea for how to prevent the duplicate from slipping in ✅

**Comment by CrendKing** [comment]
> * rename a file using the OS
> 
> * notice the new file is added to the gallery

That's exactly what I did. Thanks.

**Comment by whyboris** [comment]
🚀 I think I fixed everything: https://github.com/whyboris/Video-Hub-App/pull/573/commits/aa292b9899c5151ede9e13e40b2ce860cc0ab992

It's a hack-y approach, but it works 🤷‍♂️ 

Will merge into `main` now -- please feel free try out in a minute 😁 🤝 😎

**Comment by whyboris** [comment]
Closed with #573 -- please create a new issue if this issue persists 🤝
