### ISSUE TITLE
Main windows frozen during scan

### ISSUE THREAD

**Issue by lighthunt** [whyboris/Video-Hub-App#556]
The whole application froze after adding new folder (Let's call it "F") to scan. The only way out was to force kill it. I have tried it several time without luck. "F" folder contains several subfolders (videos and other filetypes) and picking one of the subfolders to scan worked. This means that some kind filetypes may cause the whole app to freeze.
I am sorry I don't have more details (the tree with files is huge), I will further try to isolate the problem to find out what type of files cause the issue, will see. Anyone with similar issue, please comment

**Comment by whyboris** [comment]
Thank you for bringing this up. 

I have a change in the works where I plan to separate the `chokidar` (initial scan of the whole tree) from the rest of the scan - so that the two don't interfere. I've added two `performance.now()` timestamps; the difference between them is less than 1 second on my ~1,000 of videos folder -- so `chokidar` is beautifully fast.

I think I'll keep the timing-measurements in the `main` branch so it's easier to debug and see which particular process is causing the problems 😅

**Comment by whyboris** [comment]
Unrelated -- is there a chance you have a non-English character in any of the folders?

For example the Turkish `İ` causes [a problem](https://github.com/whyboris/Video-Hub-App/issues/533#issuecomment-707890842)

**Comment by whyboris** [comment]
ps - I have an alternative extraction flow with #559 -- extracting everything in 3 _separate_ stages (currently, the last 2 stages -- meta & thumb extraction -- run in parallel). This may help isolate the problem -- to see where the error occurs (will be easier to debug on your side).

😎 as a bonus there's logging about how long each stage takes 🕐

**Comment by whyboris** [comment]
Closing as #602 should fix the problem 👍 -- will be released (likely) this weekend 👍
