### ISSUE TITLE
v3: Thumbnails of deleted videos can't be removed until restart

### ISSUE THREAD

**Issue by CrendKing** [whyboris/Video-Hub-App#580]
If I delete a video outside, then launch the app, the file monitoring will pick up the change and remove the thumbnail image from the list. However,

1. the thumbnail files on disk are still there;
2. what's worse is even if I go Setting -> Current hub -> Edit folders -> Delete old thumbnails, it can't delete anything. Sometimes restarting the app then repeat the 4 clicks will work. Sometimes even that doesn't work. I will have to leave the app open for like 2 minutes, then works.
3. what's worst is, even if I delete video inside the app (with dangerous delete enabled), the same problem is there.

Questions:

1. Can you make it so that the associated thumbnail files of a video are automatically deleted when it detects the video is gone?
2. If you can't, can you at least make it update the metadata without requiring restarting the app?

**Comment by whyboris** [comment]
I do not want to automatically delete thumbnails. This is because when a user renames a file using the OS, the app will consider the original file "deleted" and will discover a "new" file. If the screenshots are still there, there is no need for the app to re-create them (makes the process faster). 

Another example is moving video files; for example from internal hard drive to external hard drive: the video files are the same and the app will be able to re-use the same screenshots, otherwise it will have to re-extract every screenshot.

The manual delete process (clicking on the `Delete old thumbnails` button) _should_ work (and quickly!). I'll look to see why it might error out in the way you describe 🤔 🔎 I already suspect I know how to fix a part of it 😎 

The current `delete` functionality deletes all screenshots that are not part of the `imageElements` array. But when you delete an element, it isn't removed from the array, it's just marked as `deleted` - so until you close the hub (or app) and re-open it, the element is still there and the screenshot will not be removed. I'll fix this with the next PR 🤝 

For now - you could confirm that after deleting files, when you close and re-open the hub (by switching to another hub, or closing/opening the app), the app _should_ be able to delete the screenshots.

ps - I suspect if the app is in the process of adding videos to the hub and you try to delete old screenshots, it might work slower 🤔 

Sorry for the long answer. But in summary:
1) I'd rather not have auto-delete of thumbnails (see first & second paragraphs)
2) I'm unsure what metadata you want updated -- could you elaborate? It seems like the app _is_ deleting the video from the hub (deleted video is no longer visible) -- sorry for misunderstanding.

**Comment by whyboris** [comment]
bug fixed: https://github.com/whyboris/Video-Hub-App/pull/582/commits/8801d6864851e70916b14c556c5d0ea157483e61

Please comment after I merge it in if that solves the major problem and what else is left to fix 🤝 😁

**Comment by CrendKing** [comment]
We can discuss about deleting thumbnails automatically in a separate issue. The main point of this issue is that, if the video is deleted outside, and the app detects that (the image element is removed visually), I can't use the manual thumbnail deletion button without restarting. That doesn't make any sense.

**Comment by whyboris** [comment]
🤷 I've used the "delete old thumbnails" maybe once or twice on my hubs (except for the time when I was developing the feature). 

I just don't see much use in spending time on getting all the edge cases just to make automatic deletion work. I strongly suspect most users will not use the button. The inconvenience of having to restart the app _is_ an inconvenience, but a minor one in my opinion.

If it was a few lines of code, I wouldn't mind, but it will be a lot of lines of code (as far as I can tell) - and they could introduce further bugs 🤔 

If the video is deleted outside the app when the app isn't turned on, when you turn it on, you'll be able to click "Delete old thumbnails" and it will work 👍 

It may make sense to delete all old screenshots upon exiting the app, but I'd rather the app close faster. We could delete old screenshots upon opening a hub, but that would slow down the app/hub start-up time 👎 

Sorry to be resistant to improving the app in the direction you recommend, but it's a balance: any time I spend on this I won't be able to release `3.0.0` faster, and would have to delay the exciting feature I have on my roadmap (server functionality) 🤷 

I think I would be open to a PR regarding what you propose -- but please let's discuss first before anyone does any work. I am still uneasy about any kind of automatic deletion of old screenshots.

**Comment by whyboris** [comment]
I closed the issue with the #582 PR but I'm happy to continue the conversation.
Please feel free to re-open the issue too 👌
