### ISSUE TITLE
Prompt for root folder when saved root folder doesn't exist

### ISSUE THREAD

**Issue by wAuner** [whyboris/Video-Hub-App#6]
If your videohub is on a SMB share the app saves the path in windows format. On mac and linux this leads to the problem, that if you click on a video in the app, the video will not open in your default video player.

The solution would be to save the filepaths in the .vha file in a different format, depending on the operating system of the client. On Unix systems this will be the mounting point (mac: /Volumes, Linux: /Media/username/...) 
Example:
For me this was "\\\\{name_of_network_share}\\Plex_videos\\video_folder” which works on windows.
I tried it on mac and changed that path manually to the correct mounting point on my system.
In this case “/Volumes/Plex_videos/video_folder”. Now when I click a video, it opens the video in VLC as intended.

**Comment by cal2195** [comment]
Do you mean if you create a library on Windows, and then open it on Mac/Linux?

**Comment by cal2195** [comment]
If so, then yes, this won't work - it's not an easy fix as you could mount the directory anywhere on your system, and even if you mount it in the same folder like Volumes, mac can change the name if there's other mounted shares.

One solution would be to detect if the video folder is missing, and allow you to browse to the correct mount point.

If we were to have multiple video paths for the root folder, it would be better to have it per system, rather than per OS, as the path isn't guaranteed to be the same on the same OS.

**Comment by wAuner** [comment]
Good question. I can‘t remember on what os  I created the hub.
Is the mounting point really that unpredictable? Shouldn‘t it be always mounted in the same place unless you mount it manually via terminal or have a directory with the exact same name mounted?

**Comment by cal2195** [comment]
Those should be the only two cases, but they're cases we need to take care of! Especially on linux, you're likely to mount it where ever you like, and each linux distro uses different mount points (/mnt, /media, /run) so we can't predict it.

And I've had MacOS mount my folder in folder-1 because the previous mount didn't unmount properly.

I'd rather let the user choose, rather than guess and get it wrong. Alternatively you could symlink all the folders to a common place! 😅

**Comment by cal2195** [comment]
Also, this would fix a nice issue of moving your library too! 😄

**Comment by cal2195** [comment]
The problem with that is that you don't have to keep the vha file with the actual video folder - you can choose to change it in the creation wizard!

I guess if you keep them the same in the creation wizard, we could make the assumption that files are relative to the vha file... Means you couldn't move them apart though...

**Comment by cal2195** [comment]
> I guess if you keep them the same in the creation wizard, we could make the assumption that files are relative to the vha file... 

Would this fix your use case?

**Comment by wAuner** [comment]
that would do it for me. I always created the vha files directly inside the video directories.
That would be a simple and effective solution.

**Comment by cal2195** [comment]
Thanks @wAuner - I've created #7 to track this second bug.

I'll try to get it into v1.4.0! 😄
