### ISSUE TITLE
Video hub window version won't open

### ISSUE THREAD

**Issue by vinnystanley** [whyboris/Video-Hub-App#624]
Hi, I have just updated my video hub (windows version) to version 3 and now it won't open. 
![error](https://user-images.githubusercontent.com/77564188/104832809-93cdbe00-5859-11eb-8f7f-0504d6a7a148.png)

**Comment by whyboris** [comment]
Sorry for the bug. I'm unsure what the problem is. I strongly suspect that the `settings.json` file got corrupted somehow.

Please open the `Run` command (click _start_ icon and type in "run" and press the `Enter` key). There, type in `%appdata%` and press the `Enter` key - this should open up a folder `C:\Users\[YOUR USER NAME]\AppData\Roaming`

There open the `video-hub-app-2` folder and delete the `settings.json` file (or just rename it or move it to another location).

Please let me know if this resolves or does not resolve your problem 🤝

**Comment by whyboris** [comment]
For reference, on a _Mac_ the `settings.json` is located here:

`/Users/[user name]/Library/Application Support/video-hub-app-2`

**Comment by whyboris** [comment]
# Let's fix this 🎉 

We just need to wrap the `fs.readFile` in a `try` / `catch` 👌 
https://github.com/whyboris/Video-Hub-App/blob/c72117c5d5e813036b8f0ab523e5517269c6f935/main.ts#L288

Cheers 🤝

**Comment by whyboris** [comment]
@vinnystanley -- just curious, in case you remember -- when this error appeared once, when you close the error message and re-opened the app, did the app open without error and go to the "Wizard" screen? 

Because when I tested somethings that's what happened in my case - meaning the error is only a minor inconvenience 🤔 and doesn't actually prevent users from using the app.

**Comment by whyboris** [comment]
Fixed 😎
