### ISSUE TITLE
Autocomplete tags when searching

### ISSUE THREAD

**Issue by cal2195** [whyboris/Video-Hub-App#65]
It would be a very neat feature to auto complete tags when searching from the search fields! 👍 

I'm not sure how difficult this would be to implement in the current setup, but it would be worth thinking about with #53! 👍

**Comment by whyboris** [comment]
Oh yea! That's done 👌

**Comment by cal2195** [comment]
Reopening as I meant this in reference to the "tag filters"! 😄

**Comment by whyboris** [comment]
There's a bit of a tweak I'd like to work on to the _auto tag_ filters that show up in the _details_ view -- namely the 2-word auto-tags should show up as 2 words (rather than one).

I'll work on that part - and then later I can look into auto-completion of both manual and auto-tags in the sidebar search 👍

**Comment by cal2195** [comment]
I wonder if we should not remove tags that are in the "two word tags" from the "one word tags" and show both in the auto tags? 💡 

It makes sense to have both words as individual tags, but they also have a different meaning when they're used together! I meant to bring this up earlier! 👍  Thoughts?

**Comment by whyboris** [comment]
I forgot the current functionality -- I _am_ removing one-word tags that appear in two-word combinations, right?

If I did that, it was likely because if I didn't the one-word-tags would grow to be at least 2x the size. 

A user _can_ add the 1-word tags manually if wanted; I am still leaning towards not adding the 2-word tags as two separate words into the 1-word tag column.

Feels faster for the user to add a few missing ones, than having to remove a large number of duplicates. Though as usual I'm not very clear about what people are using this app for 😅

**Comment by whyboris** [comment]
Hey @cal2195 -- I'm trying to finalize the app v2.0.0 and I might encroach on your tagging feature a bit. I'm sorry ahead of time if I end up reverting some of your work -- it isn't intentional.

I've not looked at the auto-generated or manually-added tag code in over a month and don't remember how some of it behaves. I'll try to fix whatever bugs I find and add whatever features we discussed above and before (unless they end up being too complex for this release).

I'd rather get everything release-ready within a week or two so I have enough time to polish off the icons and update the website (record new animations, etc).

I'll try to get all the tag bugfixes and features into a single PR and keep it open for a while so you have a time to glance at it and give me feedback -- you've done excellent work with tags and I'd rather not overwrite your intentions 🙇 

Cheers 🤝

**Comment by cal2195** [comment]
That sounds good to me! I'll have a look through the bugs now and see what I can do to help! 👍  Let me know if you'd like me to tackle anything!

Don't worry about postponing anything new or current you'd like to be more polished - gotta have something for future releases! 😉

**Comment by whyboris** [comment]
@cal2195 you're a genius! I just noticed that if the `autoFileTags` is enabled (so they show up in blue in the _details_ / _edit meta_ view), then when you do the tag search - they _are_ part of the search, but if you _disable_ the _autoFileTags_, they are _not_ part of the search  💥 😮 🙇

**Comment by cal2195** [comment]
😇
