### ISSUE TITLE
Settings.json is not saved

### ISSUE THREAD

**Issue by CrendKing** [whyboris/Video-Hub-App#675]
With the latest commits (HEAD @ https://github.com/whyboris/Video-Hub-App/commit/26fb13b6a9387ef271b39b800d10c38b62c0c1c1), if I use the X button to close the window, everything works fine. But if I Alt+F4 the window, settings.json will be reset to 0 byte.

Maybe it has something to do with https://github.com/whyboris/Video-Hub-App/commit/268294b2ca28cbe6359184b35ad6489f2fe4413e?

**Comment by whyboris** [comment]
Thank you for keeping track of this 🙇 -- I removed `remote` because it's [_deprecated_](https://www.electronjs.org/docs/api/remote) by Electron - with the commit you point to: https://github.com/whyboris/Video-Hub-App/commit/268294b2ca28cbe6359184b35ad6489f2fe4413e#diff-856b4a4969a5de4eb6bf7ac1f8f156c7063fc7bdf68209192b7b8769e059b788L493

I thought I solved the problem by making the app save everything before it finally quit, but seems like there are some loose ends 😓 

I'll keep this _Issue_ open until I get to it to fix it. PR for a fix is also welcome 👍

**Comment by CrendKing** [comment]
If I comment out the settings.json write at https://github.com/whyboris/Video-Hub-App/commit/268294b2ca28cbe6359184b35ad6489f2fe4413e#diff-0b4a13d876020b09b600e6a8fb04f755f6d531ecb9c9a7335510da545bbe9d7bR367, no reset happens. If I change the write mode to something non-destructible like `r+`, Alt+F4 wouldn't reset to empty but sometimes reset to all default values.

So it seems this function behaves differently depending on how "close window" is invoked. Maybe Alt+F4 doesn't leave enough time for the function to execute, and it was OK before because `remote` was synchronous?

If that's the case, I wonder maybe the ultimate solution is write settings whenever a setting is changed, instead of doing one lump sum write at closing time. Same for the vha2 file I guess?

**Comment by whyboris** [comment]
There's bound to be a way to `preventDefaul()` somewhere 👌 or just properly use an _Electron_ hook somewhere like -[`beforeunload`](https://www.electronjs.org/docs/api/browser-window#event-close) 🤔 

I would rather not write the settings every time the users plays with the buttons, and especially not write a possibly large (5+ MB) `.vha2` file 😅 every time the hub gets updated (a video plays, tag is added, etc). 

I'll try to find some time this weekend to replicate the bug and then fix it 🤞 though I'm also happy if anyone prefers to fix it instead of me 🤝 🙇 😁

**Comment by CrendKing** [comment]
I spent some time on this issue. It seems if I add `event.preventDefault()` before the `getAngularToShutDown();` in [`win.on('close')`](https://github.com/whyboris/Video-Hub-App/blob/main/main.ts#L180), the problem is solved. So I think the logic you intended was

1) When the main window is about to close, intercept it, prevent it (which is currently missing), send event to try to save files.
2) When file is confirmed written, try to close the window again, with the `readyToQuit = true` set.
3) Now the event handler would actually close.

I guess because the event was not prevented, the closure still happened. So there was a race condition between the app quitting and file being saved. Since file change can't commit before quit, we got 0 byte settings.json.

**Comment by whyboris** [comment]
Thank you so much! I'll try all this out on my end. 
If you happen to have the code already, please consider opening up a PR 🙇 
And if it's not 100%, I could clean it up too - please don't feel like you have to do everything 🤝

**Comment by CrendKing** [comment]
PR: https://github.com/whyboris/Video-Hub-App/pull/694

**Comment by okumam** [comment]
I had this issue and it broke the app in weird ways for me.  Settings changes would never save anymore after some point, regardless of the exit method.  I was stuck with the settings I had a month ago.  I reinstalled and it worked.  After that, settings save if I exit with the X button, but they don't save if I exist with alt-f4, which is what my mouse gesture uses.  However, I don't get a zero length settings.json file.  It just doesn't update.

Could you also add a "save settings" button if the bug persists?  Then making changes but forgetting to hit X would be less of an issue.

**Comment by whyboris** [comment]
Closed with #694 🙇  thank you @CrendKing for the fix!
