### ISSUE TITLE
Server problem

### ISSUE THREAD

**Issue by h3r0n-github** [whyboris/Video-Hub-App#839]
I'm trying to connect to VHA server. I believe I am able to connect to it but all it shows is an empty screen with the menu buttons (zoom in/out, search, settings, refresh) on the bottom. 

I try to search but nothing comes up. 

Please help. 
![vha](https://github.com/whyboris/Video-Hub-App/assets/157181076/8e9ab4bc-af9c-4c1c-b6cc-67c01a5c0fff)

**Comment by whyboris** [comment]
Hello 👋 

Did it ever work, or was it like this always? When you start the server, there is a QR code that you use your phone on. If it worked before but stopped, perhaps your IP changed on your WiFi 🤔 If so, you could try again - use the QR code again.

Another thought: your VHA needs to continue running while using the "remote" (on your phone) - and the hub you are viewing needs to have at least some videos showing in the gallery (those are the videos that will show up on your phone). This feature is so that you can perform a filter / search in VHA and then only browse those videos when on your phone.

Also, there is a "refresh" button on bottom right in the remote - clicking it might do the trick. And finally, there is a search button in the middle of the remote -- please click it and confirm there is no text entered there (because if you enter a string that is not found in any of the video file names - you will see no results).

Please reach out if nothing works; provide more detail perhaps and I could try again ❤️

**Comment by h3r0n-github** [comment]
Thanks. It kind of worked. But in the process of fixing it, I realised that the "server" is different to what I had imagined. 

I had been inputting filter tags into the search field but realised now that it looks up file names instead.  

Also I thought I would be able to view the videos directly on my phone but it is only a remote. 

But thanks for your help nonetheless!

**Comment by whyboris** [comment]
I tried numerous times to get videos to play over the phone, but the problem I face is I'm using a PWA (Progressive Web App) which is opened via _Safari_ and it does not allow viewing videos when the content isn't coming from _HTTPS_ (which is basically a dead-end, since the app is served locally, and not over the internet).

While I _could_ create a companion _iOS_ app that will allow streaming, it would require a lot of learning on my end and I don't have the time for it right now.

_tl;dr_ - no streaming video to the phone in the foreseeable future 😢
