### ISSUE TITLE
Add versioning to the vha file

### ISSUE THREAD

**Issue by cal2195** [whyboris/Video-Hub-App#9]
Without a version field in the vha file, it's hard to work out what type of vha you are opening, and how to convert it to a new version.

We should add a version field, so that we can add backward compatibility properly. (We can assume no version means <=v1.3.0).

**Comment by whyboris** [comment]
It may now be very easy to detect the old format: just see if we have an array of arrays rather than an array of objects, or simply if the `screenshotHeight` is missing (the renamed version of the field).

I think we should not worry about this issue until we're close to releasing v2.0.0 - and then we'll see what kind of a message we'll show to the user (probably will be easiest to say "sorry this file is an old format, please re-create the hub in the new system" 😅

**Comment by cal2195** [comment]
I think we should definitely add this to the vha file for v2.0.0 - it's one field at the top, and will help with future changes! 👍 

@whyboris what do you think?
