### ISSUE TITLE
First installation welcome & walkthrough

### ISSUE THREAD

**Issue by whyboris** [whyboris/Video-Hub-App#91]
I'd like to have a welcome screen and a walkthrough for people installing the app for the first time 👍 

I'll work on it before release, after we add more features and abolish bugs 😅

**Comment by whyboris** [comment]
Feels like a large undertaking - might release after 2.0 comes out 😓

**Comment by whyboris** [comment]
Will not release along with or before version 2.0.0 🙆‍♂

**Comment by mcpalmer1980** [comment]
Adding an explanation of inclusive and exclusive filters should be included in the walkthrough. I can't figure out what these terms mean or how to use them.

**Comment by whyboris** [comment]
Thank you for the suggestion!

For now, for reference:

"inclusive" means you can search for word "hi" and "hello" at the same time and all files that have *either* "hi" *or* "hello" will show up.

"exclusive" means you can search for word "hi" and "hello" at the same time and all the files that have *both* "hi" *and* "hello" will show up.

**Comment by mcpalmer1980** [comment]
I just purchased the app for $5 because I like it so much, because you have
respond so quickly, and because building from source resulted in an
AppImage that doesn't work properly. The one you distribute to paid
customers works beautifully, however(do I smell conspiracy, probably not).

Your definitions for inclusive and exclusive are what I expected, but
perhaps you should update your github post to include instructions on how
to switch modes, and also that there is a NOT mode as well. I only just
found these options in the config dialog.

I hate js but damn Node.js is so responsive. My most used apps will now
likely be VS Code and Video Hub App, and both use it. Thankfully my current
professional project uses Dash, wrapping node.js in a nice python interface
for easy data visualization.

Thanks for such a cool app

**Comment by whyboris** [comment]
Glad to hear you like it!

Sorry about the build error -- I suspect here is the [answer](https://github.com/whyboris/Video-Hub-App/issues/312#issuecomment-554697113) (thank you for creating the [issue](https://github.com/whyboris/Video-Hub-App/issues/312))

**Comment by whyboris** [comment]
Thank you to @orkomlosh for the addition of #503 (Modal instead of system mesage) 🙌  -- this makes adding a nice welcome message a breeze 😁 

I'll add a dummy welcome message for now and then fill it in with images and descriptions for how to use the app before release (as well as a button to view the welcome message in case someone wants to).

Cheers everyone 👋
