### ISSUE TITLE
Corrupt/incomplete video files stall thumbnail extraction

### ISSUE THREAD

**Issue by cal2195** [whyboris/Video-Hub-App#97]
I've noticed with corrupt and incomplete video files, generally when the duration of the file doesn't match the real duration of the file, the thumbnail extraction stalls for a very long amount of time as ffmpeg tries to complete the extraction! This seems to be due to the filters expecting data from the inputs at each time code, and if any of these don't have data, it stalls waiting for it. There does appear a timeout, but it's incredibly long. 👎 

To counter this, we can first check each of the timecodes individually, and check for actual data! 👍 This works way quicker, and will fail immediately if the data is missing!

If we find data missing, we have three options:
1) Skip all thumbnail generation for this file. eg. 0 screenshots.
2) Generate as many thumbnails as we can until the missing data, and then update the `numOfScreenshots` for that file. eg. 15/20 screenshots.
3) Change the duration of the file to be until the first missing data, and generate the full `numOfScreenshots` for the file. eg. 20 screenshots.

Thoughts? 💡

**Comment by whyboris** [comment]
Is it not too hard to insert blank screens where screenshots were not found?

I suspect some corrupt files have local corruption (say at 50% mark there is 20 seconds of video that's missing, while all the rest is present). In that case, we'd have a full filmstrip except for a single missing screenshot (best scenario), rather than an incorrect duration as in option 3, missing screenshots as in option 1, or only half the screenshots as in 2.

Though this may be a bigger challenge.

Since I've started working on the app over a year ago, I've always been time-constrained. I always have more ideas, bug-fixes, and edge-case-handling intentions than I have time for, so I opted to work on the features that would affect the most users.

The current bug you describe is worth fixing -- using the new ffmpeg extraction we have I scanned in a folder with 300 files, and it halted at 58%. I suspect a file is corrupt (I didn't find the time to investigate further). The easiest thing to implement is likely option 1 - just skip the file generation.

Thank you for your attention to detail and constant testing of edge cases 🙇 

If there are particular features / bug fixes you'd like _me_ to work on - just let me know and I'll make them a higher priority on my todo list 👍

**Comment by cal2195** [comment]
I was having the similar experience - mine would halt at 43% and I confirmed it was corrupt files! I've implemented option 1 locally, and I'm testing it out! If it works, I will add that initially and the look into your suggestion! I think it can be done! 👍

**Comment by cal2195** [comment]
Regarding priority, I would be very grateful if you get the time to review my overall idea in #73! 😄 (See my comment)

**Comment by cal2195** [comment]
Following up on this, my implementation has much improved this! I've opted for skipping corrupt videos so far, which will additionally point out the problematic files so I can debug! 🐞 

I'm going to investigate #103 some more, and then PR the changes for this issue! 👍

**Comment by cal2195** [comment]
Closing thing for now as #109 has merged! 👍 

May return in the future to add the more complicated solutions! 💯
